file_format: "1"
id: lily59
name: Lily59
type: shield
url: https://github.com/kata0510/Lily58
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - lily59_left
  - lily59_right
  - lily59_dongle
